# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 14:49
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('desc', models.CharField(max_length=300, verbose_name='类别描述')),
                ('image', models.ImageField(upload_to='category/%Y/%m', verbose_name='封面图')),
                ('status', models.IntegerField(choices=[('1', '启用'), ('2', '禁用')], default=1, verbose_name='状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('desc', models.CharField(max_length=300, verbose_name='商品描述')),
                ('price', models.CharField(default=0, max_length=50, verbose_name='商品价格')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='商品详情')),
                ('is_index', models.BooleanField(default=False, verbose_name='是否首页')),
                ('is_act', models.BooleanField(default=False, verbose_name='是否参与活动')),
                ('image', models.ImageField(upload_to='commodity/%Y/%m', verbose_name='封面图')),
                ('tag', models.CharField(default='', max_length=20, verbose_name='商品标签')),
                ('click_nums', models.IntegerField(default=0, verbose_name='商品点击数')),
                ('status', models.IntegerField(choices=[('1', '启用'), ('2', '禁用')], default=1, verbose_name='状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Category', verbose_name='商品类别')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.StoreOrg', verbose_name='所属门店')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation', models.IntegerField(default=5, verbose_name='信誉')),
                ('service', models.IntegerField(default=5, verbose_name='服务')),
                ('desc', models.IntegerField(default=5, verbose_name='描述')),
                ('logistics', models.IntegerField(default=5, verbose_name='物流')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Commodity', verbose_name='商品')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
            },
        ),
    ]
