# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[('1', '启用'), ('2', '禁用')], null=True, verbose_name='状态'),
        ),
    ]
