# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180623_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[('1', '启用'), ('2', '禁用'), ('-1', '删除')], default=1, null=True, verbose_name='状态'),
        ),
    ]
