# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-26 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20180623_1552'),
        ('goods', '0004_auto_20180623_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '启用'), (2, '禁用'), (-1, '删除')], default=1, verbose_name='状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '门店商品列表',
                'verbose_name_plural': '门店商品列表',
            },
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='store_id',
        ),
        migrations.AddField(
            model_name='storegoods',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Commodity', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='storegoods',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.StoreOrg', verbose_name='门店'),
        ),
    ]
