# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-26 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180626_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='commodity_id',
            new_name='commodity',
        ),
        migrations.RenameField(
            model_name='storegoods',
            old_name='goods_id',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='storegoods',
            old_name='store_id',
            new_name='store',
        ),
    ]
