# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-26 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180626_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='desc',
            field=models.FloatField(default=5, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='score',
            name='logistics',
            field=models.FloatField(default=5, verbose_name='物流'),
        ),
        migrations.AlterField(
            model_name='score',
            name='reputation',
            field=models.FloatField(default=5, verbose_name='信誉'),
        ),
        migrations.AlterField(
            model_name='score',
            name='service',
            field=models.FloatField(default=5, verbose_name='服务'),
        ),
    ]
