# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20180626_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='image',
            field=models.ImageField(null=True, upload_to='commodity/%Y/%m', verbose_name='封面图'),
        ),
    ]
