# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-06 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180701_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='city_id',
            new_name='city',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='company',
            field=models.CharField(default='', max_length=300, verbose_name='公司名称'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='postal_code',
            field=models.IntegerField(default=0, max_length=100, verbose_name='邮编'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='town',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='镇'),
        ),
    ]
