# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-06 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_useraddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='姓'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='名'),
        ),
    ]
