# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-06 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20180706_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.IntegerField(default=0, verbose_name='邮编'),
        ),
    ]
