# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-06 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20180706_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='address',
            new_name='shou_address',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='last_name',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='shou_name',
            field=models.CharField(default='', max_length=50, verbose_name='姓名'),
        ),
    ]
