# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_auto_20180706_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='status',
            field=models.IntegerField(choices=[(1, '成功'), (0, '未支付'), (-1, '取消')], default=0, verbose_name='订单状态'),
        ),
    ]
