# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-11 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20180629_1740'),
        ('operation', '0010_usercourse_nums'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShouCustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shou_name', models.CharField(default='', max_length=100, verbose_name='收货人')),
                ('shou_phone', models.IntegerField(max_length=15, verbose_name='收货人手机号')),
                ('shou_address', models.CharField(default='', max_length=500, verbose_name='收货地址')),
                ('post_code', models.IntegerField(max_length=20, verbose_name='邮政编码')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.CityDict', verbose_name='城市')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.UserCourse', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单收件地址',
                'verbose_name_plural': '订单收件地址',
            },
        ),
    ]
