# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-11 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_shoucustomerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoucustomerinfo',
            name='post_code',
            field=models.IntegerField(default=10086, verbose_name='邮政编码'),
        ),
        migrations.AlterField(
            model_name='shoucustomerinfo',
            name='shou_phone',
            field=models.IntegerField(default=0, verbose_name='收货人手机号'),
        ),
    ]
