# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-11 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_auto_20180711_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoucustomerinfo',
            name='shou_phone',
            field=models.CharField(default=0, max_length=11, verbose_name='收货人手机号'),
        ),
    ]
