# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-18 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_shoppingbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingbase',
            name='all_price',
            field=models.IntegerField(default=0, verbose_name='商品总价'),
        ),
    ]
