# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-19 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0015_shoppingbase_all_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomments',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='评级'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='评论'),
        ),
    ]
