# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('1', '启用'), ('2', '禁用')], default=1, verbose_name='状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '门店下员工',
                'verbose_name_plural': '门店下员工',
            },
        ),
        migrations.CreateModel(
            name='StoreOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='门店名称')),
                ('desc', models.TextField(verbose_name='门店描述')),
                ('category', models.CharField(choices=[('xx', '线下'), ('xn', '虚拟')], default='xn', max_length=20, verbose_name='门店类型')),
                ('image', models.ImageField(upload_to='Store/%Y/%m', verbose_name='封面图')),
                ('address', models.CharField(max_length=150, verbose_name='门店地址')),
                ('tag', models.CharField(default='优秀', max_length=10, verbose_name='机构标签')),
                ('status', models.IntegerField(choices=[('1', '启用'), ('2', '禁用')], default=1, verbose_name='状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '门店机构',
                'verbose_name_plural': '门店机构',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.StoreOrg', verbose_name='所属门店'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='员工ID'),
        ),
    ]
