# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20180623_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeorg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Store/%Y/%m', verbose_name='封面图'),
        ),
    ]
